# Generated by Django 5.2.4 on 2025-08-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_blockedip_requestlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("guest", "Guest"),
                    ("customer", "Customer"),
                    ("admin", "Admin"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
